## &nbsp;&nbsp;&nbsp;&nbsp;С#. Исключительные ситуации и их обработка
### &nbsp;&nbsp;&nbsp;&nbsp;Исключительные ситуации

&nbsp;&nbsp;&nbsp;&nbsp;Базовым для всех типов исключений является тип Exception. Этот тип определяет ряд свойств, с помощью которых можно получить информацию об исключении.

+ &nbsp;&nbsp;&nbsp;&nbsp;**InnerException**: хранит информацию об исключении, которое послужило причиной текущего исключения

+ &nbsp;&nbsp;&nbsp;&nbsp;**Message**: хранит сообщение об исключении, текст ошибки

+ &nbsp;&nbsp;&nbsp;&nbsp;**Source**: хранит имя объекта или сборки, которое вызвало исключение

+ &nbsp;&nbsp;&nbsp;&nbsp;**StackTrace**: возвращает строковое представление стека вызывов, которые привели к возникновению исключения

+ &nbsp;&nbsp;&nbsp;&nbsp;**TargetSite**: возвращает метод, в котором и было вызвано исключение

```
try
{
    int x = 5;
    int y = x / 0;
    Console.WriteLine($"Результат: {y}");
}
catch (Exception ex)
{
    Console.WriteLine($"Исключение: {ex.Message}");
    Console.WriteLine($"Метод: {ex.TargetSite}");
    Console.WriteLine($"Трассировка стека: {ex.StackTrace}");
}
```

>Есть более специализированные типы исключений, которые предназначены для обработки каких-то определенных видов исключений. Их довольно много, я приведу лишь некоторые:

+ &nbsp;&nbsp;&nbsp;&nbsp;**DivideByZeroException**: представляет исключение, которое генерируется при делении на ноль

+ &nbsp;&nbsp;&nbsp;&nbsp;**ArgumentOutOfRangeException**: генерируется, если значение аргумента находится вне диапазона допустимых значений

+ &nbsp;&nbsp;&nbsp;&nbsp;**ArgumentException**: генерируется, если в метод для параметра передается некорректное значение

+ &nbsp;&nbsp;&nbsp;&nbsp;**IndexOutOfRangeException**: генерируется, если индекс элемента массива или коллекции находится вне диапазона допустимых значений

+ &nbsp;&nbsp;&nbsp;&nbsp;**InvalidCastException**: генерируется при попытке произвести недопустимые преобразования типов

+ &nbsp;&nbsp;&nbsp;&nbsp;**NullReferenceException**: генерируется при попытке обращения к объекту, который равен null (то есть по сути неопределен)

---

### &nbsp;&nbsp;&nbsp;&nbsp;Обработка исключений
>&nbsp;&nbsp;&nbsp;&nbsp;Иногда при выполнении программы возникают ошибки, которые трудно предусмотреть или предвидеть, а иногда и вовсе невозможно. Например, при передачи файла по сети может неожиданно оборваться сетевое подключение. такие ситуации называются исключениями.  

&nbsp;&nbsp;&nbsp;&nbsp;Язык C# предоставляет разработчикам возможности для обработки таких ситуаций. Для этого в C# предназначена конструкция try...catch...finally.
```
try
{
     
}
catch
{
     
}
finally
{
     
}
```
&nbsp;&nbsp;&nbsp;&nbsp;При использовании блока try...catch..finally вначале выполняются все инструкции в блоке try. Если в этом блоке не возникло исключений, то после его выполнения начинает выполняться блок finally. И затем конструкция try..catch..finally завершает свою работу.  